project:
  type: website
  output-dir: docs
  
website:
  title: "Computational Oncology"
  search: 
    location: navbar
    type: overlay
    
  favicon:  contents/logo/helix/favicon.ico
  site-url: https://componco.github.io/lab_website.github.io/

  navbar:
    background: primary
    logo: contents/logo/helix/DNA_scaled.png
    search: true
    right:
      - icon: twitter
        href: https://twitter.com/aedinculhane
        aria-label: Twitter
      - icon: github
        href: https://github.com/CompOnco/lab_website/
        aria-label: GitHub

        
    left:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: projects.qmd
      - text: "People"
        file:  people.qmd
      - text: "Collaborate"
        file:  Collaborate.qmd
      - text: "News"
        file: news.qmd
      - text: "Publications"
        menu:
          - publications.qmd         
          - talks.qmd
      - text: "Software"
        file: software.qmd
      - text: "Join Us"
        file: positions.qmd

  sidebar:
    contents:
      - section: News
        contents: News
      - section: People
        contents: People
        
    style: "docked"
    tools:
      - icon: twitter
        href: https://twitter.com/aedinculhane
      - icon: github
        menu:
          - text: Report a Bug
            url:  https://github.com/CompOnco/lab_website/issues

  body-footer: 
    file: footer.qmd
  
  page-footer:
    left: 
      - text: "@Culhane Lab"
    center:
      - text: "People"
        href: people.qmd
      - text: "Research"
        href: projects.qmd
      - text: "News"
        href: news.qmd
      - icon: twitter
        href: https://twitter.com/aedinculhane
        aria-label: CulhaneLab Twitter
      - icon: github
        href: https://github.com/CompOnco/lab_website/
        aria-label: CulhaneLab GitHub
    right: UL 
     [![](contents/logo/LDCRC_Logo_fixed.jpg){fig-alt="LDCRC" width=150px}]
      
      
    
repo-url: https://github.com/CompOnco
repo-actions: [edit, issue]
  

  
twitter-card: 
  creator: "@AedinCulhane"
  site: "@CulhaneLab"

open-graph: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


editor: visual

