project:
  type: website
  output-dir: docs
  
website:
  title: "Culhane Lab"
  search: 
    location: navbar
    type: overlay
  reader-mode: true
  favicon:  contents/logo/helix/favicon.ico
  site-url: https://componco.github.io/lab_website.github.io/

  navbar:
    background: primary
    logo: contents/logo/helix/DNA_scaled.png
    search: true
    right:
      - icon: twitter
        href: https://twitter.com/aedinculhane
        aria-label: Twitter
      - icon: github
        href: https://github.com/CompOnco/lab_website/
        aria-label: GitHub

        
    left:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: projects.qmd
      - text: "People"
        file:  people.qmd
      - text: "Collaborate"
        file:  Collaborate.qmd
      - text: "News"
        file: news.qmd
      - text: "Publications"
        menu:
          - publications.qmd         
          - talks.qmd
      - text: "Software"
        file: software.qmd
      - text: "Join Us"
        file: positions.qmd

  sidebar:
    contents:
      - People
      - News
        
    style: "docked"
    tools:
      - icon: twitter
        href: https://twitter.com/aedinculhane
      - icon: github
        menu:
          - text: Report a Bug
            url:  https://github.com/CompOnco/lab_website/issues

  
  page-footer:
    left: 
      - text: "@Culhane Lab"
    center: |
      ![](contents/logo/LDCRC_Logo_fixed.jpg "Limerick Digital Cancer Research Center"){height="40"}
      ![](contents/logo/bioconductor_logo_cmyk.png "Bioconductor"){height="40"}
      ![](contents/logo/eHealthHub_logo.png "eHealthHub For Cancer"){height="40"}
      ![](contents/logo/Elixir_logo-3927606181.png "ELIXIR"){height="40"}
      ![](contents/logo/OHDSI.jpeg "OHDSI Real World Data"){height="40"}
      ![](contents/logo/NasPro.png "National Spatial Tissue Profiling Platform"){height="40"}
      ![](contents/logo/NSRP_Logo.png){height="40"}
    right: |
     ![](contents/logo/LDCRC_Logo_fixed.jpg){fig-alt="LDCRC" width=150px}


    
repo-url: https://github.com/CompOnco
repo-actions: [edit, issue]
  

  
twitter-card: 
  creator: "@AedinCulhane"
  site: "@CulhaneLab"

open-graph: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


editor: visual

